import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { plusJakartaSans } from "@/lib/utils";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PCMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-neutral-white ${plusJakartaSans.className}`}>{children}</body>
    </html>
  );
}
